In [67]:
import pandas as pd

In [68]:
amazon = pd.read_csv("amazon.csv")

In [69]:
amazon

,Name,Author,User Rating,Reviews,Price,Price_r,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,$8.00,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,$22.00,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,$15.00,15,2018,Non Fiction
3,1984,George Orwell,4.7,70425,$7.48,8,2021,Fiction
4,1984 (Signet Classics),George Orwell,4.7,21424,$6.00,6,2017,Fiction
...,...,...,...,...,...,...,...,...
645,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,$8.00,8,2019,Fiction
646,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2016,Non Fiction
647,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2017,Non Fiction
648,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2018,Non Fiction
649,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,$8.00,8,2019,Non Fiction

## Preguntas

Por aÃ±o cuantos libros ha publicado un autor, recuerde que los aÃ±os no trabajados deberia de aparecer en cero. considere como primer registro por autor el primer aÃ±o en que publico y el ultimo el aÃ±o maximo encontrado.

Ejemplo, si Uayeb public en 2009 dos libros, y en 2011 tres. y esas son las dos unicas entradas para este autor. la salida para el deberia de ser:

In [70]:
pd.DataFrame({ "Autor" : ["Uayeb","Uayeb","Uayeb"] , "Year" : [2009,2010,2011]  , "Conteo" : [2,0,3] })

   Autor  Year  Conteo
0  Uayeb  2009       2
1  Uayeb  2010       0
2  Uayeb  2011       3

In [71]:
df_temp = amazon.loc[ : , ('Author','Year')]
df_temp["Conteo"] = 0
df_temp = df_temp.groupby(['Author','Year'], as_index=False).agg({ "Conteo" : ["count"] }).sort_values('Author')
df_temp.columns = df_temp.columns.droplevel(1)
df_temp

                 Author  Year  Conteo
0      Abraham Verghese  2010       1
1      Abraham Verghese  2011       1
2        Adam Gasiewski  2017       1
3         Adam Mansbach  2011       1
4          Adam Silvera  2021       1
..                  ...   ...     ...
584  Wonder House Books  2021       1
585  Workman Publishing  2020       2
586  Workman Publishing  2021       1
587        Zhi Gang Sha  2009       1
588        Zhi Gang Sha  2013       1

[589 rows x 3 columns]

Que Autores han trabado en un aÃ±o en mas de un libro

Ejemplo de salida esperada:

In [72]:
pd.DataFrame({
    
    "Autor" : ['Uayeb','Imix']
    , "Year" : [2010, 2010]
    , "Conteo de Titulos" : [2 , 3]
    
})

   Autor  Year  Conteo de Titulos
0  Uayeb  2010                  2
1   Imix  2010                  3

In [73]:
df_temp1 = df_temp.loc[df_temp["Conteo"] != 1, :]
df_temp1.columns = ["Author" , "Year","Conteo de Titulos"]
df_temp1 = df_temp1.sort_values('Author')
df_temp1

                     Author  Year  Conteo de Titulos
5              Adam Wallace  2020                  2
16            Amanda Gorman  2021                  2
58          Bill Martin Jr.  2020                  2
61            Bill O'Reilly  2012                  2
67       Blue Star Coloring  2015                  2
85         Charlaine Harris  2009                  2
128              Dav Pilkey  2018                  3
129              Dav Pilkey  2019                  3
140         David Zinczenko  2009                  2
163               Dr. Seuss  2015                  2
169  Dr. Steven R Gundry MD  2018                  2
173               E L James  2012                  4
254              Glenn Beck  2009                  2
263              Harper Lee  2015                  2
285            J.K. Rowling  2016                  4
297             Jeff Kinney  2009                  2
322           Joanna Gaines  2018                  2
326         Johanna Basford  2015                  2
330              John Green  2014                  3
346        Kathryn Stockett  2011                  2
360       Laura Hillenbrand  2014                  2
369        Malcolm Gladwell  2009                  2
380         Marjorie Sarnat  2015                  2
441               RH Disney  2014                  2
443           Rachel Hollis  2019                  2
458            Rick Riordan  2012                  2
456            Rick Riordan  2010                  4
457            Rick Riordan  2011                  2
462             Rob Elliott  2013                  2
463             Rob Elliott  2014                  2
464             Rob Elliott  2015                  2
485               Rupi Kaur  2017                  2
520            Stephen King  2013                  2
528         Stephenie Meyer  2009                  6
533           Stieg Larsson  2009                  2
534           Stieg Larsson  2010                  3
538         Suzanne Collins  2010                  3
539         Suzanne Collins  2011                  4
540         Suzanne Collins  2012                  4
571           Veronica Roth  2013                  2
572           Veronica Roth  2014                  2
585      Workman Publishing  2020                  2

Que genero por aÃ±o ha obtenido el mejor rating en promedio. (solo deberia de obtener un registro por aÃ±o)

- ejemplo de la salida esperada:

In [74]:
pd.DataFrame({
    "Year" : [2009,2010]
    , "Genre" : [ "Fiction" , "Fiction" ]
    , "Mean User Rating": [ 4.59 , 4.61 ]
})

   Year    Genre  Mean User Rating
0  2009  Fiction              4.59
1  2010  Fiction              4.61

In [75]:
df_temp2 = amazon.loc[ : , ("Year","Genre","User Rating")]
df_temp2 = df_temp2.groupby(["Year","Genre"], as_index=False)["User Rating"].mean()
df_temp2 = df_temp2.iloc[df_temp2.groupby('Year').agg(max_ = ('User Rating', lambda data: data.idxmax())).max_]
df_temp2.columns = ["Year","Genre","Mean User Rating"]
df_temp2

    Year        Genre  Mean User Rating
0   2009      Fiction          4.591667
2   2010      Fiction          4.615000
4   2011      Fiction          4.619048
7   2012  Non Fiction          4.558621
9   2013  Non Fiction          4.561538
10  2014      Fiction          4.631034
12  2015      Fiction          4.652941
14  2016      Fiction          4.715789
16  2017      Fiction          4.737500
18  2018      Fiction          4.738095
20  2019      Fiction          4.820000
23  2020  Non Fiction          4.737037
25  2021  Non Fiction          4.746154

Cuales son los autores que por lo menos dos aÃ±os consecutivos hayan tenido en promedio ratings que decrecen 

Ejemplo

- Si Uayeb caballero, en 2010 saco dos libros, y el rating de esos dos libros es de 3.1, ese mismo autor en 2011 en su unico libro publicado ese aÃ±o su promedio fue de 2.9 y en 2012 sus tres libros publicados en promedio su rating es de 2.8. Podemos ver que son dos aÃ±os que este usuario ha ido decreciendo 

No importa que haya publicado en aÃ±os salteados, ejemplo, 2010 si, 2011 no, 2012 no, 2013 si, 2014 si. para este caso el analisis comienza en 2010, 2013 y 2014

Ejemplo de salida esperada:

In [76]:
pd.DataFrame({ "autores" : ['Uayeb','Imix'] })

  autores
0   Uayeb
1    Imix

Cuales son los libros que por aÃ±o se encuentran arriba del percentil 70. (Sin importar genero)

Ejemplo de salida esperada

In [77]:
pd.DataFrame({
    "Year": [2010,2010,2011,2011]
    , "Titulos": ["Libro A","Libro B","Libro Z","Libro Y"]
    , "Autor": ["Autor 1","Autor 2","Autor 1","Autor 3"]
    , "Rating": [4.1, 4.0,4.2,4.3]
    , "Rating .70": [3.8,3.8,3.7,3.7]
})

   Year  Titulos    Autor  Rating  Rating .70
0  2010  Libro A  Autor 1     4.1         3.8
1  2010  Libro B  Autor 2     4.0         3.8
2  2011  Libro Z  Autor 1     4.2         3.7
3  2011  Libro Y  Autor 3     4.3         3.7

Este ejemplo es para que se haga una idea de la estructura de salida esperada, claramente por aÃ±o dependiendo de las publicaciones pueden haber varios libros arriba del percentil 70